### ISSUE TITLE
[아이템6] 어댑터

### ISSUE THREAD

**Issue by chldbtjd2272** [CleanCodeStudy/ReadingRecord#10]
어댑터에 대한 설명좀

**Comment by csbsjy** [comment]
함께 동작할 수 없는 두 클래스를 연결해주는 역할을 하는걸 어댑터라고 해. 예를들어, Client가 A 인터페이스를 잘 쓰고 있었는데 중간에 다른 써드파티 라이브러리로 변경하게 된다면 기존의 A라는 인터페이스를 수정하는 방법을 쓰지 않고 중간에 어댑터 인터페이스를 만들어서 A 인터페이스는 어댑터 인터페이스에게 요청을하고 이 어댑터는 써드파티 라이브러리에게 요청을 위임하는거야.  https://yaboong.github.io/design-pattern/2018/10/15/adapter-pattern/ 이 예제가 좀 좋았어. 근데 이게 왜 아이템 6에 언급된건지 잘 모르겠어 ㅎㅎㅎㅎㅎㅎㅎㅎㅎ
