### ISSUE TITLE
[아이템 10] List 의 contains 메서드  

### ISSUE THREAD

**Issue by csbsjy** [CleanCodeStudy/ReadingRecord#13]
> p55. list.contains(s)를 호출하면 JDK 버전에 따라 다르게 나올 수도 있다. equals 규약을 어기면 그 객체를 사용하는 다른 객체들이 어떻게 반응할지 알 수 없다.

여기서 구현하기 나름, JDK 버전에 따라 달라질 수 있다는 얘기가 잘 와닿지가 않아. list contains 메서드가 버전마다 다르게 구현되어있다는건가 이해가 잘 안되넵 ..!

**Comment by mjung1798** [comment]
ArrayList의 contains 구현체 (JDK 8)

        public boolean contains(Object o) {
            return indexOf(o) >= 0;
        }
    
        /**
         * Returns the index of the first occurrence of the specified element
         * in this list, or -1 if this list does not contain the element.
         * More formally, returns the lowest index <tt>i</tt> such that
         * <tt>(o==null&nbsp;?&nbsp;get(i)==null&nbsp;:&nbsp;o.equals(get(i)))</tt>,
         * or -1 if there is no such index.
         */
        public int indexOf(Object o) {
            if (o == null) {
                for (int i = 0; i < size; i++)
                    if (elementData[i]==null)
                        return i;
            } else {
                for (int i = 0; i < size; i++)
                    if (o.equals(elementData[i]))
                        return i;
            }
            return -1;
        }

For 문 같은 경우는 list를 하나하나 돌면서 객체를 하나하나 접근해서 Index를 찾는거구.

여기서 equals를 사용함.

CaseInsensitiveString 의 equals 를 구현할 때 equalsIgnoreCase 를 이용했으니까 false가 잘 나오는데.

혹시모르지 다른 버전에서는 ArrayList의 contains에 index를 찾아서 비교하는 방식으로 한 , indexOf() 를 사용한 방식이 아니거나. equals를 사용하지 않고 그냥 ==을 사용했거나 다를 수 도 있을 것 같음.



Java 1 : 제네릭을 지원하지 않아서 List<>에 들어갈 수가 없음

Java 5 : 여기서부터 indexOf() 로 구현해둠 - 여기서부터 제네릭 지원

Java 6 : 마찬가지 - 여기서부터 @override 지원

Java 7 : 마찬가지

Java 8 : 디버거로 contains 찍으면 위의 indexOf() 부분

**Comment by mjung1798** [comment]
근데 진짜 확인해보니까 모든 버전의 list.contains() 가 같게 구현되어있는데... 흠...
추후에 버그가 생기면, indexOf 방식이 아니라 다른 방식을 사용할 수도 있다 이런걸 내포하는건가 싶음

**Comment by mjung1798** [comment]
https://github.com/mjung1798/Jyami-Java-Lab/tree/master/effectiveJava/src/main/java/item10/containsJDK
