### ISSUE TITLE
[아이템 10] 필드의 표준형을 저장해두고 표준형끼리 비교하라

### ISSUE THREAD

**Issue by csbsjy** [CleanCodeStudy/ReadingRecord#14]
>  p63. CaseInsensitiveString 예처럼 비교하기가 아주 복잡한 필드는 그 필드의 표준형을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다.

이해가 잘 안가는데 예시좀 !

**Comment by mjung1798** [comment]
https://stackoverflow.com/questions/33992000/canonical-form-of-field

**Comment by mjung1798** [comment]
https://github.com/mjung1798/Jyami-Java-Lab/blob/master/effectiveJava/src/main/java/item10/canonicalForm
