### ISSUE TITLE
[아이템10] 값을 추가하지 않는 방식으로 Point를 확장하는 법에서

### ISSUE THREAD

**Issue by pci2676** [CleanCodeStudy/ReadingRecord#15]
>p59 상속대신 컴포지션을 사용하라

이렇게 구현하는 경우 리스코프 치환원칙은 깨지게 되는게 아니야? 결국 CounterPoint와 Point는 상속관계가 없어지기 때문에 CounterPoint를 Point처럼 사용할 수 없게되잖아..? 매번 `asPoint()`라는 메서드를 호출해서 사용해야 한다고 받아들여 지는데.. 
그냥 trade off 라고 생각하면 되는 건가??

**Comment by mjung1798** [comment]
리스코프의 치환원칙은 안깨지는 것 같아 왜냐면 일단 리스코프의 치환원칙의 전제는 하위타입과 상위타입의 관계인데, 여기서는 그런의미가 아니었으니까.
code 10-5면 ColorPoint 맞지?
여기서의 목적은 ColorPoint끼리의 색상비교도 하고싶었던건데, 만약 리스코프 치환원칙을 지키려고 상속을 하게 되면 ColorPoint에 equals를 쓸 때 문제가 많이 생기니까 합성(composition)으로 우회하는 방법을 사용함

[상속을 사용할 때] : 상위 클래스인 Point의 equals만 사용하는 것이 권장사항
Point - Point 비교 가능
ColorPoint - Point 비교 가능 : 그러나 x, y 비교만 하게될것
ColorPoint - ColorPoint 비교 가능 : 그러나 x, y 비교만 하게될것

[합성을 사용할 때] : point와 colorpoint의 역할을 분리해서 비교가 가능함
Point - Point 비교 가능 (x,y 비교)
ColorPoint - Point 비교 가능 : asPoint를 사용해서 ColorPoint를 Point로 바꾼 후에 비교 -> 이경우 결국 상속했을 때 리스코프 치환원칙을 따라서 비교한 것과 같은 효과가 남.
ColorPoint - ColorPoint 비교 가능 : (x, y, color 비교)
