### ISSUE TITLE
[아이템10] 58p SmellPoint와 ColorPoint

### ISSUE THREAD

**Issue by chldbtjd2272** [CleanCodeStudy/ReadingRecord#17]
이거 왜 무한재귀가 일어나?

**Comment by mjung1798** [comment]
> 56p

**Comment by mjung1798** [comment]
// ColorPoint.java
    	@Override
        public boolean equals(Object o) {
            if(!(o instanceof Point))
                return false;
    
            if(!(o instanceof ColorPoint))
                return o.equals(this);
    
            return super.equals(o) && ((ColorPoint) o).color == color;
        }
    

    // SmellPoint.java
    	@Override
        public boolean equals(Object o) {
            if(!(o instanceof Point))
                return false;
    
            if(!(o instanceof SmellPoint))
                return o.equals(this);
    
            return super.equals(o);
        }

ColorPoint랑 SmellPoint 둘다 Point를 상속받은 클래스라서

o instanceof Point 이 부분은 통과하고 실질적인 비교를

if(!(o instance of SmellPoint)

if(!(o instance of ColorPoint)

이 두줄로 하게 되는데 서로가 서로를 호출하게 됌!

ColorPoint 에서 o.equals(this)니까 SmellPoint인 o를 호출해서 o.equals 즉, SmellPoint의 equals를 호출하고,

SmellPoint 에서도 o.equals(this)니까 ColorPoint인 o를 호출해서 o.equals 즉, ColorPoint의 equals를 호출함!

이게 서로 반복된다요!

**Comment by mjung1798** [comment]
실행 가능한 코드 링크
https://github.com/mjung1798/Jyami-Java-Lab/tree/master/effectiveJava/src/main/java/item10/infiniteRecursion
