### ISSUE TITLE
[아이템1] Jdbc 예제( 정적 팩토리 메서드를 작성하는 시점에는 구현체가 없어도 된다)

### ISSUE THREAD

**Issue by chldbtjd2272** [CleanCodeStudy/ReadingRecord#3]
Jdbc 구현체 드라이버 등록하고 get하는 부분 자바 예제로 만들어서 디버깅 해서 보여주세여

**Comment by csbsjy** [comment]
커밋 확인해주세욤. 이거 말하는게 맞는지 모르겠네~ 디버그는 아직 안찍어봐서 일단 클로즈안할게
