### ISSUE TITLE
[아이템1] 세번째 장점에서 Collections을 예제로든 이유

### ISSUE THREAD

**Issue by Gobukgol** [CleanCodeStudy/ReadingRecord#5]
> p.9, 반환타입의 하위타입 객체를 반환할 수 있는 능력이 있다.

**Comment by csbsjy** [comment]
나는 장점 3이 정적팩터리메서드는 인터페이스, 추상클래스를 반환값으로 가질 수 있다는 것을 말하는 걸로 이해했거든. 그냥 SuperClass 일수도 있겠지만 .. 어쨋든 내 생각엔 Collections 클래스는 List, Set, Map 타입을 반환하는 정적팩터리메서드가 있고 반환값을 그 하위 타입으로 캐스팅 할 수 있게 함으로써 더 유연한 시스템이 될 수 있는걸 보여줄 수 있는 좋은 예제.. 인거같다고 생각한거 아닐까 ..?
